steps:
  - label: ":fsociety: Install Dependencies"
    commands:
      - "scripts/install_deps.sh"
      - "scripts/cache_upload.sh"
    key: install-deps

  - label: ":fsociety: Static Analysis"
    commands:
      - "scripts/cache_download.sh"
      - "scripts/format_check.sh"
      - "scripts/lint_check.sh"
    key: static-analysis
    agents:
      nix: "true"
    depends_on:
      - install-deps

  - label: ":test_tube: Unit & E2E Tests"
    commands:
      - "scripts/cache_download.sh"
      - "scripts/unit_tests.sh"
      - "scripts/e2e_tests.sh"
    if: "!build.pull_request.draft"
    key: tests
    agents:
      nix: "true"
    depends_on:
      - static-analysis

  - label: ":fly-io: Deploy"
    command: "scripts/deploy.sh"
    branches: "main"
    concurrency: 1
    concurrency_group: "oberan/deploy"
    agents:
      nix: "true"
    depends_on:
      - tests
