steps:
  - label: ":fsociety: Static Analysis"
    commands:
      - "scripts/install_deps.sh"
      - "scripts/format_check.sh"
      - "scripts/lint_check.sh"
    key: static-analysis

  - label: ":test_tube: Unit & E2E Tests"
    commands:
      - "scripts/install_deps.sh"
      - "scripts/unit_tests.sh"
      - "scripts/e2e_tests.sh"
    if: "!build.pull_request.draft"
    key: tests
    depends_on:
      - static-analysis

  - label: ":fly-io: Deploy"
    command: "scripts/deploy.sh"
    branches: "main"
    key: deploy
    depends_on:
      - tests
