version: v1.0

name: Auto-promote fly deploy

agent:
  machine:
    type: e2-standard-2
    os_image: ubuntu2204

blocks:
  - name: "\U0001F680 Deploy to Fly.io"
    task:
      secrets:
        - name: flyio
      prologue:
        commands:
          - checkout
      jobs:
        - name: build and deploy
          commands:
            - curl -L https://fly.io/install.sh | sh
            - echo "export FLYCTL_INSTALL='/home/semaphore/.fly'" >> ~/.bash_profile
            - echo "export PATH='$FLYCTL_INSTALL/bin:$PATH'" >> ~/.bash_profile
            - source ~/.bash_profile
            - flyctl deploy --remote-only
