version: v1.0

name: Auto-promote fly deploy

agent:
  machine:
    type: e2-standard-2
    os_image: ubuntu2204

blocks:
  - name: "\U0001F680 Deploy to Fly.io"
    task:
      secrets:
        - name: flyio
      prologue:
        commands:
          - checkout
      jobs:
        - name: build and deploy
          commands:
            - curl -L https://fly.io/install.sh | sh
            - ls -al $HOME
            # - echo "export FLYCTL_INSTALL='/home/semaphore/.fly'" >> $HOME/.bash_profile
            # - echo "export PATH='$FLYCTL_INSTALL/bin:$PATH'" >> $HOME/.bash_profile
            # - source $HOME/.bash_profile
            - export FLYCTL_INSTALL="/home/semaphore/.fly"
            - export PATH="$FLYCTL_INSTALL/bin:$PATH"
            - flyctl deploy --remote-only
